# -*- coding: utf-8 -*-
"""Building 1st AI Project-ITCS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mmEU3viRVi9VvWbxGgV7UG041vG4E_y6

##Loading the data

scikit learn stores the dataset for iris flowers
"""

from sklearn.datasets import load_iris
import numpy as np

iris= load_iris()

x=iris.data
y=iris.target

x.shape

y.shape

iris.feature_names

iris.target_names

"""##Splitting into training and test sets

"""

from sklearn.model_selection import train_test_split

#random_state=42 determines that shuffling between samples is determiistic

x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=42)

"""##Choosing and Training a model

"""

#We will be using a decision tree classifier. Helps to classify the features easily and is easy to visualise.
#They work well on small datasets

"""##Initialising the model"""

from sklearn.tree import DecisionTreeClassifier

model=DecisionTreeClassifier(random_state=42)

"""##Train the model (Fitting the model)"""

model.fit(x_train, y_train)

"""##Making predictions (Evaluating Model)"""

y_pred=model.predict(x_test)

y_pred

#Inspecting how models are doing
print("Predictions:",y_pred)
print("True Labels:", y_test)

#Evaluating the model
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

accuracy=accuracy_score(y_test, y_pred)
print("Accuracy:",accuracy)

matrix=confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n",matrix)

precision= precision_score(y_test,y_pred, average='micro')
print("Precision:",precision)

recall=recall_score(y_test, y_pred, average='micro')
print("Recall:",recall)

f1=f1_score(y_test, y_pred, average='micro')
print("F1 Score:",f1)

class_report=classification_report(y_test, y_pred)
print("Classification Report:\n",class_report)

from sklearn.tree import plot_tree
import matplotlib.pyplot as plt

plt.figure(figsize=(10,10))
plot_tree(model, feature_names=iris.feature_names, class_names=iris.target_names, filled=True)
plt.show()

"""##Trying with KNN"""

from sklearn.neighbors import KNeighborsClassifier

model_knn=KNeighborsClassifier(n_neighbors=5)

model_knn.fit(x_train, y_train)

y_predknn=model_knn.predict(x_test)

print("Predictions:",y_predknn)
print("True Labels:", y_test)

accuracy_knn=accuracy_score(y_test, y_predknn)
print("Accuracy:",accuracy_knn)



